/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author diego
 */
public class frmTerminarPartida extends javax.swing.JFrame {

    /**
     * Creates new form frmTerminarPartida
     */
    public frmTerminarPartida() {
        initComponents();
        personalizarComponentes();
        setResizable(false);
        setLocationRelativeTo(null); // Centrar la ventana en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("JUEGO TERMINADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalizarComponentes() {
        // Cambiar el fondo del JFrame
        getContentPane().setBackground(new Color(30, 30, 50)); // Fondo oscuro

        // Personalizar el texto del JLabel
        jLabel1.setFont(new Font("Arial", Font.BOLD, 32)); // Fuente más grande
        jLabel1.setForeground(Color.WHITE); // Color blanco para resaltar
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER); // Centrar el texto
        jLabel1.setVerticalAlignment(SwingConstants.CENTER); // Centrar verticalmente

        // Establecer diseño en el JFrame para centrar el JLabel
        setLayout(new BorderLayout());
        add(jLabel1, BorderLayout.CENTER);

        // Revalidar y repintar para aplicar cambios
        revalidate();
        repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
