/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import com.id.dtos_sh.NaveDTO;
import com.id.dtos_sh.TableroDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus Eduardo Villanueva Godoy 235078
 * @author Jose Alan Manjarrez Ontiveros 228982
 */
public class frmTablero extends javax.swing.JFrame {

    graphicTableInicio grapi;
    graphicNaves gnav;
    TableroDTO tablero;

    /**
     * Creates new form frmTablero
     */
    public frmTablero() {
        initComponents();
        agregarNaves();
        llenarTablero();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTablero = new javax.swing.JPanel();
        btnListo = new javax.swing.JButton();
        jBarcos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 2, 36)); // NOI18N
        jLabel1.setText("Batalla naval");

        javax.swing.GroupLayout jTableroLayout = new javax.swing.GroupLayout(jTablero);
        jTablero.setLayout(jTableroLayout);
        jTableroLayout.setHorizontalGroup(
            jTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        jTableroLayout.setVerticalGroup(
            jTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        btnListo.setText("Listo");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBarcosLayout = new javax.swing.GroupLayout(jBarcos);
        jBarcos.setLayout(jBarcosLayout);
        jBarcosLayout.setHorizontalGroup(
            jBarcosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jBarcosLayout.setVerticalGroup(
            jBarcosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jBarcos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        if (gnav.todasLasNavesColocadas()) {
            // Obtener las posiciones de las naves colocadas
            List<NaveDTO> navesColocadas = grapi.obtenerNavesConPosiciones();

            // Mostrar las naves colocadas en la consola (puedes manejar esto como necesites)
            for (NaveDTO nave : navesColocadas) {
                System.out.println("Nave: " + nave.getTipo());
                System.out.println("Posición inicial: (" + nave.getCasilla().getCoordenada().getX()
                                   + ", " + nave.getCasilla().getCoordenada().getY() + ")");
                System.out.println("Dirección: " + nave.getDireccion());
                System.out.println("Longitud: " + nave.getLongitud());
            }

            JOptionPane.showMessageDialog(this, "¡Todas las naves han sido colocadas correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar mensaje de error si faltan naves por colocar
            JOptionPane.showMessageDialog(this, "Faltan naves por colocar en el tablero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListoActionPerformed

    public void llenarTablero() {
        tablero = new TableroDTO();
        tablero.setTamaño(10);
        grapi = new graphicTableInicio(tablero,gnav,"Verde");

        jTablero.setLayout(new BorderLayout());
        jTablero.add(grapi, BorderLayout.CENTER);

        jTablero.setBorder(BorderFactory.createLineBorder(Color.RED));
        grapi.setBorder(BorderFactory.createLineBorder(Color.BLUE));

        jTablero.revalidate();
        jTablero.repaint();
    }
    
    public void agregarNaves() {
        List<NaveDTO> naves = graphicNaves.obtenerBarcosPorDefecto();

        // Crear el panel para las naves gráficas
        gnav = new graphicNaves(naves,"Verde");

        // Configurar el diseño de jBarcos para que sea vertical
        jBarcos.setLayout(new BoxLayout(jBarcos, BoxLayout.Y_AXIS));
        jBarcos.add(gnav); // Añade el panel de naves al contenedor
        jBarcos.setBorder(BorderFactory.createTitledBorder("Naves disponibles")); // Agregar borde para visualización

        jBarcos.revalidate();
        jBarcos.repaint();
    }
    
    public static void main(String[] args) {
        // Establecer la apariencia de la interfaz (opcional)
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Crear y mostrar la ventana
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTablero().setVisible(true); // Muestra la ventana de batalla naval
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListo;
    private javax.swing.JPanel jBarcos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jTablero;
    // End of variables declaration//GEN-END:variables
}
